apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exporter-ingress
  namespace: exporter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: prometheus
            port:
              number: 9090
        path: /prom/?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: exporter2
            port:
              number: 8080
        path: /exporter/?(.*)
        pathType: ImplementationSpecific
